"""Independent risk engine (no Freqtrade dependency)."""

from stat_arb.risk.risk import (
    CooldownConfig,
    CooldownTracker,
    EntryDecision,
    ExposureCheckResult,
    ExposureConfig,
    MarketRegime,
    PositionSide,
    PositionSizeResult,
    PositionSizingConfig,
    RegimeConfig,
    RiskEngine,
    RiskEngineConfig,
    RiskError,
    StopLossConfig,
    TrendFilterConfig,
    TrendFilterResult,
    calculate_position_size,
    check_exposure_limits,
    compute_stop_loss_price,
    compute_trend_filter,
    detect_regime,
    is_stop_loss_triggered,
)

__all__ = [
    "CooldownConfig",
    "CooldownTracker",
    "EntryDecision",
    "ExposureCheckResult",
    "ExposureConfig",
    "MarketRegime",
    "PositionSide",
    "PositionSizeResult",
    "PositionSizingConfig",
    "RegimeConfig",
    "RiskEngine",
    "RiskEngineConfig",
    "RiskError",
    "StopLossConfig",
    "TrendFilterConfig",
    "TrendFilterResult",
    "calculate_position_size",
    "check_exposure_limits",
    "compute_stop_loss_price",
    "compute_trend_filter",
    "detect_regime",
    "is_stop_loss_triggered",
]
